#lang racket
(require ffi/unsafe)
(require "llvm/ffi/all.rkt")
(require "jit-env.rkt")
(require "jit-type.rkt")

(provide jit-lookup-pass
         jit-lookup-attr)

(define (jit-lookup-pass p)
  (hash-ref jit-pass-map p))
(define (jit-lookup-attr a)
  (hash-ref jit-attr-map a))
(define jit-pass-map
  (make-hash
     ;;Scaler transformations
   `((AggressiveDCE                         . ,LLVMAddAggressiveDCEPass)
     (BitTrackingDCE                        . ,LLVMAddBitTrackingDCEPass)
     (AlignmentFromAssumptions              . ,LLVMAddAlignmentFromAssumptionsPass)
     (CFGSimplification                     . ,LLVMAddCFGSimplificationPass)
     (DeadStoreElimination                  . ,LLVMAddDeadStoreEliminationPass)
     (Scalarizer                            . ,LLVMAddScalarizerPass)
     (MergedLoadStoreMotion                 . ,LLVMAddMergedLoadStoreMotionPass)
     (GVN                                   . ,LLVMAddGVNPass)
     (IndVarSimplify                        . ,LLVMAddIndVarSimplifyPass)
     (InstructionCombining                  . ,LLVMAddInstructionCombiningPass)
     (JumpThreading                         . ,LLVMAddJumpThreadingPass)
     (LICM                                  . ,LLVMAddLICMPass)
     (LoopDeletion                          . ,LLVMAddLoopDeletionPass)
     (LoopIdiom                             . ,LLVMAddLoopIdiomPass)
     (LoopRotate                            . ,LLVMAddLoopRotatePass)
     (LoopReroll                            . ,LLVMAddLoopRerollPass)
     (LoopUnroll                            . ,LLVMAddLoopUnrollPass)
     (LoopUnswitch                          . ,LLVMAddLoopUnswitchPass)
     (MemCpyOpt                             . ,LLVMAddMemCpyOptPass)
     (PartiallyInlineLibCalls               . ,LLVMAddPartiallyInlineLibCallsPass)
     (LowerSwitch                           . ,LLVMAddLowerSwitchPass)
     (PromoteMemoryToRegister               . ,LLVMAddPromoteMemoryToRegisterPass)
     (Reassociate                           . ,LLVMAddReassociatePass)
     (SCCP                                  . ,LLVMAddSCCPPass)
     (ScalarReplAggregates                  . ,LLVMAddScalarReplAggregatesPass)
     (ScalarReplAggregatesPassSSA           . ,LLVMAddScalarReplAggregatesPassSSA)
     (ScalarReplAggregatesPassWithThreshold . ,LLVMAddScalarReplAggregatesPassWithThreshold)
     (SimplifyLibCalls                      . ,LLVMAddSimplifyLibCallsPass)
     (TailCallElimination                   . ,LLVMAddTailCallEliminationPass)
     (ConstantPropagation                   . ,LLVMAddConstantPropagationPass)
     (DemoteMemoryToRegister                . ,LLVMAddDemoteMemoryToRegisterPass)
     (Verifier                              . ,LLVMAddVerifierPass)
     (CorrelatedValuePropagation            . ,LLVMAddCorrelatedValuePropagationPass)
     (EarlyCSE                              . ,LLVMAddEarlyCSEPass)
     (LowerExpectIntrinsic                  . ,LLVMAddLowerExpectIntrinsicPass)
     (TypeBasedAliasAnalysis                . ,LLVMAddTypeBasedAliasAnalysisPass)
     (ScopedNoAliasAA                       . ,LLVMAddScopedNoAliasAAPass)
     (BasicAliasAnalysis                    . ,LLVMAddBasicAliasAnalysisPass)

     ;; Vectorization transformations
     (BBVectorize                           . ,LLVMAddBBVectorizePass)
     (LoopVectorize                         . ,LLVMAddLoopVectorizePass)
     (SLPVectorize                          . ,LLVMAddSLPVectorizePass)

     ;;Interprocedural transformations
     (ArgumentPromotion                     . ,LLVMAddArgumentPromotionPass)
     (ConstantMerge                         . ,LLVMAddConstantMergePass)
     (DeadArgElimination                    . ,LLVMAddDeadArgEliminationPass)
     (FunctionAttrs                         . ,LLVMAddFunctionAttrsPass)
     (FunctionInlining                      . ,LLVMAddFunctionInliningPass)
     (AlwaysInliner                         . ,LLVMAddAlwaysInlinerPass)
     (GlobalDCE                             . ,LLVMAddGlobalDCEPass)
     (GlobalOptimizer                       . ,LLVMAddGlobalOptimizerPass)
     (IPConstantPropagation                 . ,LLVMAddIPConstantPropagationPass)
     (PruneEH                               . ,LLVMAddPruneEHPass)
     (IPSCCP                                . ,LLVMAddIPSCCPPass)
     (Internalize                           . ,LLVMAddInternalizePass)
     (StripDeadPrototypes                   . ,LLVMAddStripDeadPrototypesPass)
     (StripSymbols                          . ,LLVMAddStripSymbolsPass))))

(define jit-attr-map
  (make-hash
   `((ZExt            . LLVMZExtAttribute)
     (SExt            . LLVMSExtAttribute)
     (NoReturn        . LLVMNoReturnAttribute)
     (InReg           . LLVMInRegAttribute)
     (StructRet       . LLVMStructRetAttribute)
     (NoUnwind        . LLVMNoUnwindAttribute)
     (NoAlias         . LLVMNoAliasAttribute)
     (ByVal           . LLVMByValAttribute)
     (Nest            . LLVMNestAttribute)
     (ReadNone        . LLVMReadNoneAttribute)
     (ReadOnly        . LLVMReadOnlyAttribute)
     (NoInline        . LLVMNoInlineAttribute)
     (AlwaysInline    . LLVMAlwaysInlineAttribute)
     (OptimizeForSize . LLVMOptimizeForSizeAttribute)
     (StackProtect    . LLVMStackProtectAttribute)
     (StackProtectReq . LLVMStackProtectReqAttribute)
     (Alignment       . LLVMAlignment)
     (NoCapture       . LLVMNoCaptureAttribute)
     (NoRedZone       . LLVMNoRedZoneAttribute)
     (NoImplicitFloat . LLVMNoImplicitFloatAttribute)
     (Naked           . LLVMNakedAttribute)
     (InlineHint      . LLVMInlineHintAttribute)
     (StackAlignment  . LLVMStackAlignment)
     (ReturnsTwice    . LLVMReturnsTwice)
     (UWTable         . LLVMUWTable)
     (NonLazyBind     . LLVMNonLazyBind))))
