#lang racket

(require
  "define.rkt"
  "ctypes.rkt")

(require ffi/unsafe)

(provide (all-defined-out))

;;general api
(define-llvm LLVMTypeOf (_fun LLVMValueRef -> LLVMTypeRef))
(define-llvm LLVMGetValueName (_fun LLVMValueRef -> _string))
(define-llvm LLVMSetValueName (_fun LLVMValueRef _string -> _void))
(define-llvm LLVMDumpValue (_fun LLVMValueRef -> _void))
(define-llvm LLVMPrintValueToString (_fun LLVMValueRef -> _string))
(define-llvm LLVMReplaceAllUsesWith (_fun LLVMValueRef LLVMValueRef -> _void))
(define-llvm LLVMIsConstant (_fun LLVMValueRef -> LLVMBool))
(define-llvm LLVMIsUndef (_fun LLVMValueRef -> LLVMBool))
(define-llvm LLVMIsAMDNode (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMIsAMDString (_fun LLVMValueRef -> LLVMValueRef))

;;user value
(define-llvm LLVMGetOperand (_fun LLVMValueRef _uint -> LLVMValueRef))
(define-llvm LLVMGetOperandUse (_fun LLVMValueRef _uint -> LLVMUseRef))
(define-llvm LLVMSetOperand (_fun LLVMValueRef _uint LLVMValueRef -> _void))
(define-llvm LLVMGetNumOperands (_fun LLVMValueRef -> _int))

;;usage
(define-llvm LLVMGetFirstUse (_fun LLVMValueRef -> LLVMUseRef))
(define-llvm LLVMGetNextUse (_fun LLVMUseRef -> LLVMUseRef))
(define-llvm LLVMGetUser (_fun LLVMUseRef -> LLVMValueRef))
(define-llvm LLVMGetUsedValue (_fun LLVMUseRef -> LLVMValueRef))

;;constants
(define-llvm LLVMConstNull (_fun LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstAllOnes (_fun LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMGetUndef (_fun LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMIsNull (_fun LLVMValueRef -> LLVMBool))
(define-llvm LLVMConstPointerNull (_fun LLVMTypeRef -> LLVMValueRef))

;;  scalar constants
(define-llvm LLVMConstInt (_fun LLVMTypeRef _ullong LLVMBool -> LLVMValueRef))
(define-llvm LLVMConstIntOfArbitraryPrecision (_fun LLVMTypeRef _uint _uint64 -> LLVMValueRef))
(define-llvm LLVMConstIntOfString (_fun LLVMTypeRef _string _uint8 -> LLVMValueRef))
(define-llvm LLVMConstIntOfStringAndSize (_fun LLVMTypeRef _string _uint _uint8 -> LLVMValueRef))
(define-llvm LLVMConstReal (_fun LLVMTypeRef _double -> LLVMValueRef))
(define-llvm LLVMConstRealOfString (_fun LLVMTypeRef _string -> LLVMValueRef))
(define-llvm LLVMConstRealOfStringAndSize (_fun LLVMTypeRef _string _uint -> LLVMValueRef))
(define-llvm LLVMConstIntGetZExtValue (_fun LLVMValueRef -> _ullong))
(define-llvm LLVMConstIntGetSExtValue (_fun LLVMValueRef -> _llong))
(define-llvm LLVMConstRealGetDouble (_fun LLVMValueRef (pointer-to LLVMBool) -> _double))

;; composite constants
(define-llvm LLVMConstStringInContext (_fun LLVMContextRef _string _uint LLVMBool -> LLVMValueRef))
(define-llvm LLVMConstString (_fun _string _uint LLVMBool -> LLVMValueRef))
(define-llvm LLVMIsConstantString (_fun LLVMValueRef -> LLVMBool))
(define-llvm LLVMGetAsString (_fun LLVMValueRef (pointer-to _size) -> _string))
(define-llvm LLVMConstStructInContext (_fun LLVMContextRef (pointer-to LLVMValueRef) _uint LLVMBool -> LLVMValueRef))
(define-llvm LLVMConstStruct (_fun (pointer-to LLVMValueRef) _uint LLVMBool -> LLVMValueRef))
(define-llvm LLVMConstArray (_fun LLVMTypeRef (pointer-to LLVMValueRef) _uint -> LLVMValueRef))
(define-llvm LLVMConstNamedStruct (_fun LLVMTypeRef (pointer-to LLVMValueRef) _uint -> LLVMValueRef))
(define-llvm LLVMGetElementAsConstant (_fun LLVMValueRef _uint -> LLVMValueRef))
(define-llvm LLVMConstVector (_fun (pointer-to LLVMValueRef) _uint -> LLVMValueRef))

;; constant expressions
(define-llvm LLVMGetConstOpcode (_fun LLVMValueRef -> LLVMOpcode))
(define-llvm LLVMAlignOf (_fun LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMSizeOf (_fun LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstNeg (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstNSWNeg (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstNUWNeg (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstFNeg (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstNot (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstAdd (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstNSWAdd (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstNUWAdd (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstFAdd (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstSub (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstNSWSub (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstNUWSub (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstFSub (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstMul (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstNSWMul (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstNUWMul (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstFMul (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstUDiv (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstSDiv (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstExactSDiv (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstFDiv (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstURem (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstSRem (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstFRem (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstAnd (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstOr (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstXor (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstICmp (_fun LLVMIntPredicate LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstFCmp (_fun LLVMRealPredicate LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstShl (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstLShr (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstAShr (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstGEP (_fun LLVMValueRef (pointer-to LLVMValueRef) _uint -> LLVMValueRef))
(define-llvm LLVMConstInBoundsGEP (_fun LLVMValueRef (pointer-to LLVMValueRef) _uint -> LLVMValueRef))
(define-llvm LLVMConstTrunc (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstSExt (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstZExt (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstFPTrunc (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstFPExt (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstUIToFP (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstSIToFP (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstFPToUI (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstFPToSI (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstPtrToInt (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstIntToPtr (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstBitCast (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstAddrSpaceCast (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstZExtOrBitCast (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstSExtOrBitCast (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstTruncOrBitCast (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstPointerCast (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstIntCast (_fun LLVMValueRef LLVMTypeRef LLVMBool -> LLVMValueRef))
(define-llvm LLVMConstFPCast (_fun LLVMValueRef LLVMTypeRef -> LLVMValueRef))
(define-llvm LLVMConstSelect (_fun LLVMValueRef LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstExtractElement (_fun LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstInsertElement (_fun LLVMValueRef LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstShuffleVector (_fun LLVMValueRef LLVMValueRef LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMConstExtractValue (_fun LLVMValueRef (pointer-to unsigned) _uint -> LLVMValueRef))
(define-llvm LLVMConstInsertValue (_fun LLVMValueRef LLVMValueRef (pointer-to unsigned) _uint -> LLVMValueRef))
(define-llvm LLVMConstInlineAsm (_fun LLVMTypeRef _string _string LLVMBool LLVMBool -> LLVMValueRef))
(define-llvm LLVMBlockAddress (_fun LLVMValueRef LLVMBasicBlockRef -> LLVMValueRef))


;; global values
(define-llvm LLVMGetGlobalParent (_fun LLVMValueRef -> LLVMModuleRef))
(define-llvm LLVMIsDeclaration (_fun LLVMValueRef -> LLVMBool))
(define-llvm LLVMGetLinkage (_fun LLVMValueRef -> LLVMLinkage))
(define-llvm LLVMSetLinkage (_fun LLVMValueRef LLVMLinkage -> _void))
(define-llvm LLVMGetSection (_fun LLVMValueRef -> _string))
(define-llvm LLVMSetSection (_fun LLVMValueRef _string -> _void))
(define-llvm LLVMGetVisibility (_fun LLVMValueRef -> LLVMVisibility))
(define-llvm LLVMSetVisibility (_fun LLVMValueRef LLVMVisibility -> _void))
(define-llvm LLVMGetDLLStorageClass (_fun LLVMValueRef -> LLVMDLLStorageClass))
(define-llvm LLVMSetDLLStorageClass (_fun LLVMValueRef LLVMDLLStorageClass -> _void))
(define-llvm LLVMHasUnnamedAddr (_fun LLVMValueRef -> LLVMBool))
(define-llvm LLVMSetUnnamedAddr (_fun LLVMValueRef LLVMBool -> _void))
(define-llvm LLVMGetAlignment (_fun LLVMValueRef -> unsigned))
(define-llvm LLVMSetAlignment (_fun LLVMValueRef _uint -> _void))

;; global variables
(define-llvm LLVMAddGlobal (_fun LLVMModuleRef LLVMTypeRef _string -> LLVMValueRef))
(define-llvm LLVMAddGlobalInAddressSpace (_fun LLVMModuleRef LLVMTypeRef _string _uint -> LLVMValueRef))
(define-llvm LLVMGetNamedGlobal (_fun LLVMModuleRef _string -> LLVMValueRef))
(define-llvm LLVMGetFirstGlobal (_fun LLVMModuleRef -> LLVMValueRef))
(define-llvm LLVMGetLastGlobal (_fun LLVMModuleRef -> LLVMValueRef))
(define-llvm LLVMGetNextGlobal (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMGetPreviousGlobal (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMDeleteGlobal (_fun LLVMValueRef -> _void))
(define-llvm LLVMGetInitializer (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMSetInitializer (_fun LLVMValueRef LLVMValueRef -> _void))
(define-llvm LLVMIsThreadLocal (_fun LLVMValueRef -> LLVMBool))
(define-llvm LLVMSetThreadLocal (_fun LLVMValueRef LLVMBool -> _void))
(define-llvm LLVMIsGlobalConstant (_fun LLVMValueRef -> LLVMBool))
(define-llvm LLVMSetGlobalConstant (_fun LLVMValueRef LLVMBool -> _void))
(define-llvm LLVMGetThreadLocalMode (_fun LLVMValueRef -> LLVMThreadLocalMode))
(define-llvm LLVMSetThreadLocalMode (_fun LLVMValueRef LLVMThreadLocalMode -> _void))
(define-llvm LLVMIsExternallyInitialized (_fun LLVMValueRef -> LLVMBool))
(define-llvm LLVMSetExternallyInitialized (_fun LLVMValueRef LLVMBool -> _void))

;; global alias
(define-llvm LLVMAddAlias (_fun LLVMModuleRef LLVMTypeRef LLVMValueRef _string -> LLVMValueRef))

;; function values
(define-llvm LLVMDeleteFunction (_fun LLVMValueRef -> _void))
(define-llvm LLVMGetPersonalityFn (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMSetPersonalityFn (_fun LLVMValueRef LLVMValueRef -> _void))
(define-llvm LLVMGetIntrinsicID (_fun LLVMValueRef -> unsigned))
(define-llvm LLVMGetFunctionCallConv (_fun LLVMValueRef -> unsigned))
(define-llvm LLVMSetFunctionCallConv (_fun LLVMValueRef _uint -> _void))
(define-llvm LLVMGetGC (_fun LLVMValueRef -> _string))
(define-llvm LLVMSetGC (_fun LLVMValueRef _string -> _void))
(define-llvm LLVMAddFunctionAttr (_fun LLVMValueRef LLVMAttribute -> _void))
(define-llvm LLVMAddTargetDependentFunctionAttr (_fun LLVMValueRef _string _string -> _void))
(define-llvm LLVMGetFunctionAttr (_fun LLVMValueRef -> LLVMAttribute))
(define-llvm LLVMRemoveFunctionAttr (_fun LLVMValueRef LLVMAttribute -> _void))

;; function parameters
(define-llvm LLVMCountParams (_fun LLVMValueRef -> unsigned))
(define-llvm LLVMGetParams (_fun LLVMValueRef (pointer-to LLVMValueRef) -> _void))
(define-llvm LLVMGetParam (_fun LLVMValueRef _uint -> LLVMValueRef))
(define-llvm LLVMGetParamParent (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMGetFirstParam (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMGetLastParam (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMGetNextParam (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMGetPreviousParam (_fun LLVMValueRef -> LLVMValueRef))
(define-llvm LLVMAddAttribute (_fun LLVMValueRef LLVMAttribute -> _void))
(define-llvm LLVMRemoveAttribute (_fun LLVMValueRef LLVMAttribute -> _void))
(define-llvm LLVMGetAttribute (_fun LLVMValueRef -> LLVMAttribute))
(define-llvm LLVMSetParamAlignment (_fun LLVMValueRef _uint -> _void))
