#lang racket
(require ffi/unsafe)
(require "ffi/all.rkt")

(provide lookup-pass
         lookup-attribute)

(define (lookup-pass p)
  (hash-ref pass-table p))
(define (lookup-attribute a context)
  (LLVMCreateEnumAttribute
   context
   (LLVMGetEnumAttributeKindForName (symbol->string (hash-ref attr-table a)))
   0))
(define pass-table
  (make-hash
     ;;Scaler transformations
   `((AggressiveDCE                         . ,LLVMAddAggressiveDCEPass)
     (BitTrackingDCE                        . ,LLVMAddBitTrackingDCEPass)
     (AlignmentFromAssumptions              . ,LLVMAddAlignmentFromAssumptionsPass)
     (CFGSimplification                     . ,LLVMAddCFGSimplificationPass)
     (DeadStoreElimination                  . ,LLVMAddDeadStoreEliminationPass)
     (Scalarizer                            . ,LLVMAddScalarizerPass)
     (MergedLoadStoreMotion                 . ,LLVMAddMergedLoadStoreMotionPass)
     (GVN                                   . ,LLVMAddGVNPass)
     (IndVarSimplify                        . ,LLVMAddIndVarSimplifyPass)
     (InstructionCombining                  . ,LLVMAddInstructionCombiningPass)
     (JumpThreading                         . ,LLVMAddJumpThreadingPass)
     (LICM                                  . ,LLVMAddLICMPass)
     (LoopDeletion                          . ,LLVMAddLoopDeletionPass)
     (LoopIdiom                             . ,LLVMAddLoopIdiomPass)
     (LoopRotate                            . ,LLVMAddLoopRotatePass)
     (LoopReroll                            . ,LLVMAddLoopRerollPass)
     (LoopUnroll                            . ,LLVMAddLoopUnrollPass)
     (LoopUnswitch                          . ,LLVMAddLoopUnswitchPass)
     (MemCpyOpt                             . ,LLVMAddMemCpyOptPass)
     (PartiallyInlineLibCalls               . ,LLVMAddPartiallyInlineLibCallsPass)
     (LowerSwitch                           . ,LLVMAddLowerSwitchPass)
     (PromoteMemoryToRegister               . ,LLVMAddPromoteMemoryToRegisterPass)
     (Reassociate                           . ,LLVMAddReassociatePass)
     (SCCP                                  . ,LLVMAddSCCPPass)
     (ScalarReplAggregates                  . ,LLVMAddScalarReplAggregatesPass)
     (ScalarReplAggregatesPassSSA           . ,LLVMAddScalarReplAggregatesPassSSA)
     (ScalarReplAggregatesPassWithThreshold . ,LLVMAddScalarReplAggregatesPassWithThreshold)
     (SimplifyLibCalls                      . ,LLVMAddSimplifyLibCallsPass)
     (TailCallElimination                   . ,LLVMAddTailCallEliminationPass)
     (ConstantPropagation                   . ,LLVMAddConstantPropagationPass)
     (DemoteMemoryToRegister                . ,LLVMAddDemoteMemoryToRegisterPass)
     (Verifier                              . ,LLVMAddVerifierPass)
     (CorrelatedValuePropagation            . ,LLVMAddCorrelatedValuePropagationPass)
     (EarlyCSE                              . ,LLVMAddEarlyCSEPass)
     (LowerExpectIntrinsic                  . ,LLVMAddLowerExpectIntrinsicPass)
     (TypeBasedAliasAnalysis                . ,LLVMAddTypeBasedAliasAnalysisPass)
     (ScopedNoAliasAA                       . ,LLVMAddScopedNoAliasAAPass)
     (BasicAliasAnalysis                    . ,LLVMAddBasicAliasAnalysisPass)

     ;; Vectorization transformations
     (BBVectorize                           . ,LLVMAddBBVectorizePass)
     (LoopVectorize                         . ,LLVMAddLoopVectorizePass)
     (SLPVectorize                          . ,LLVMAddSLPVectorizePass)

     ;;Interprocedural transformations
     (ArgumentPromotion                     . ,LLVMAddArgumentPromotionPass)
     (ConstantMerge                         . ,LLVMAddConstantMergePass)
     (DeadArgElimination                    . ,LLVMAddDeadArgEliminationPass)
     (FunctionAttrs                         . ,LLVMAddFunctionAttrsPass)
     (FunctionInlining                      . ,LLVMAddFunctionInliningPass)
     (AlwaysInliner                         . ,LLVMAddAlwaysInlinerPass)
     (GlobalDCE                             . ,LLVMAddGlobalDCEPass)
     (GlobalOptimizer                       . ,LLVMAddGlobalOptimizerPass)
     (IPConstantPropagation                 . ,LLVMAddIPConstantPropagationPass)
     (PruneEH                               . ,LLVMAddPruneEHPass)
     (IPSCCP                                . ,LLVMAddIPSCCPPass)
     (Internalize                           . ,LLVMAddInternalizePass)
     (StripDeadPrototypes                   . ,LLVMAddStripDeadPrototypesPass)
     (StripSymbols                          . ,LLVMAddStripSymbolsPass))))

(define attr-table
  (make-hash
   `((AlwaysInline                . alwaysinline)
     (SanitizeAddress             . sanitize_address)
     (ArgMemOnly                  . argmemonly)
     (Builtin                     . builtin)
     (ByVal                       . byval)
     (Convergent                  . convergent)
     (SwiftError                  . swifterror)
     (SwiftSelf                   . swiftself)
     (InaccessibleMemOnly         . inaccessiblememonly)
     (InaccessibleMemOrArgMemOnly . inaccessiblemem_or_argmemonly)
     (InAlloca                    . inalloca)
     (InlineHint                  . inlinehint)
     (InReg                       . inreg)
     (JumpTable                   . jumptable)
     (MinSize                     . minsize)
     (Naked                       . naked)
     (Nest                        . nest)
     (NoAlias                     . noalias)
     (NoBuiltin                   . nobuiltin)
     (NoCapture                   . nocapture)
     (NoDuplicate                 . noduplicate)
     (NoImplicitFloat             . noimplicitfloat)
     (NoInline                    . noinline)
     (NonLazyBind                 . nonlazybind)
     (NonNull                     . nonnull)
     (NoRedZone                   . noredzone)
     (NoReturn                    . noreturn)
     (NoRecurse                   . norecurse)
     (NoUnwind                    . nounwind)
     (OptimizeNone                . optnone)
     (OptimizeForSize             . optsize)
     (ReadNone                    . readnone)
     (ReadOnly                    . readonly)
     (WriteOnly                   . writeonly)
     (Returned                    . returned)
     (ReturnsTwice                . returns_twice)
     (SExt                        . signext)
     (Speculatable                . speculatable)
     (StackProtect                . ssp)
     (StackProtectReq             . sspreq)
     (StackProtectStrong          . sspstrong)
     (SafeStack                   . safestack)
     (StructRet                   . sret)
     (SanitizeThread              . sanitize_thread)
     (SanitizeMemory              . sanitize_memory)
     (UWTable                     . uwtable)
     (ZExt                        . zeroext)
     (Cold                        . cold))))
