#lang racket
(require ffi/unsafe)
(require "ffi/all.rkt")

(provide lookup-pass
         lookup-attribute)

(define (lookup-pass p)
  (hash-ref pass-table p))
(define (lookup-attribute a context)
  (LLVMCreateEnumAttribute
   context
   (LLVMGetEnumAttributeKindForName (symbol->string a))
   0))
(define pass-table
  (make-hash
     ;;Scaler transformations
   `((AggressiveDCE                         . ,LLVMAddAggressiveDCEPass)
     (BitTrackingDCE                        . ,LLVMAddBitTrackingDCEPass)
     (AlignmentFromAssumptions              . ,LLVMAddAlignmentFromAssumptionsPass)
     (CFGSimplification                     . ,LLVMAddCFGSimplificationPass)
     (DeadStoreElimination                  . ,LLVMAddDeadStoreEliminationPass)
     (Scalarizer                            . ,LLVMAddScalarizerPass)
     (MergedLoadStoreMotion                 . ,LLVMAddMergedLoadStoreMotionPass)
     (GVN                                   . ,LLVMAddGVNPass)
     (IndVarSimplify                        . ,LLVMAddIndVarSimplifyPass)
     (InstructionCombining                  . ,LLVMAddInstructionCombiningPass)
     (JumpThreading                         . ,LLVMAddJumpThreadingPass)
     (LICM                                  . ,LLVMAddLICMPass)
     (LoopDeletion                          . ,LLVMAddLoopDeletionPass)
     (LoopIdiom                             . ,LLVMAddLoopIdiomPass)
     (LoopRotate                            . ,LLVMAddLoopRotatePass)
     (LoopReroll                            . ,LLVMAddLoopRerollPass)
     (LoopUnroll                            . ,LLVMAddLoopUnrollPass)
     (LoopUnswitch                          . ,LLVMAddLoopUnswitchPass)
     (MemCpyOpt                             . ,LLVMAddMemCpyOptPass)
     (PartiallyInlineLibCalls               . ,LLVMAddPartiallyInlineLibCallsPass)
     (LowerSwitch                           . ,LLVMAddLowerSwitchPass)
     (PromoteMemoryToRegister               . ,LLVMAddPromoteMemoryToRegisterPass)
     (Reassociate                           . ,LLVMAddReassociatePass)
     (SCCP                                  . ,LLVMAddSCCPPass)
     (ScalarReplAggregates                  . ,LLVMAddScalarReplAggregatesPass)
     (ScalarReplAggregatesPassSSA           . ,LLVMAddScalarReplAggregatesPassSSA)
     (ScalarReplAggregatesPassWithThreshold . ,LLVMAddScalarReplAggregatesPassWithThreshold)
     (SimplifyLibCalls                      . ,LLVMAddSimplifyLibCallsPass)
     (TailCallElimination                   . ,LLVMAddTailCallEliminationPass)
     (ConstantPropagation                   . ,LLVMAddConstantPropagationPass)
     (DemoteMemoryToRegister                . ,LLVMAddDemoteMemoryToRegisterPass)
     (Verifier                              . ,LLVMAddVerifierPass)
     (CorrelatedValuePropagation            . ,LLVMAddCorrelatedValuePropagationPass)
     (EarlyCSE                              . ,LLVMAddEarlyCSEPass)
     (LowerExpectIntrinsic                  . ,LLVMAddLowerExpectIntrinsicPass)
     (TypeBasedAliasAnalysis                . ,LLVMAddTypeBasedAliasAnalysisPass)
     (ScopedNoAliasAA                       . ,LLVMAddScopedNoAliasAAPass)
     (BasicAliasAnalysis                    . ,LLVMAddBasicAliasAnalysisPass)

     ;; Vectorization transformations
     (LoopVectorize                         . ,LLVMAddLoopVectorizePass)
     (SLPVectorize                          . ,LLVMAddSLPVectorizePass)

     ;;Interprocedural transformations
     (ArgumentPromotion                     . ,LLVMAddArgumentPromotionPass)
     (ConstantMerge                         . ,LLVMAddConstantMergePass)
     (DeadArgElimination                    . ,LLVMAddDeadArgEliminationPass)
     (FunctionAttrs                         . ,LLVMAddFunctionAttrsPass)
     (FunctionInlining                      . ,LLVMAddFunctionInliningPass)
     (AlwaysInliner                         . ,LLVMAddAlwaysInlinerPass)
     (GlobalDCE                             . ,LLVMAddGlobalDCEPass)
     (GlobalOptimizer                       . ,LLVMAddGlobalOptimizerPass)
     (IPConstantPropagation                 . ,LLVMAddIPConstantPropagationPass)
     (PruneEH                               . ,LLVMAddPruneEHPass)
     (IPSCCP                                . ,LLVMAddIPSCCPPass)
     (Internalize                           . ,LLVMAddInternalizePass)
     (StripDeadPrototypes                   . ,LLVMAddStripDeadPrototypesPass)
     (StripSymbols                          . ,LLVMAddStripSymbolsPass))))

(define attr-table
  (make-hash
   `((alwaysinline                . alwaysinline)
     (sanitizeaddress             . sanitize_address)
     (argmemonly                  . argmemonly)
     (builtin                     . builtin)
     (byval                       . byval)
     (convergent                  . convergent)
     (swifterror                  . swifterror)
     (swiftself                   . swiftself)
     (inaccessiblememonly         . inaccessiblememonly)
     (inaccessiblememorargmemonly . inaccessiblemem_or_argmemonly)
     (inalloca                    . inalloca)
     (inlinehint                  . inlinehint)
     (inreg                       . inreg)
     (jumptable                   . jumptable)
     (minsize                     . minsize)
     (naked                       . naked)
     (nest                        . nest)
     (noalias                     . noalias)
     (nobuiltin                   . nobuiltin)
     (nocapture                   . nocapture)
     (noduplicate                 . noduplicate)
     (noimplicitfloat             . noimplicitfloat)
     (noinline                    . noinline)
     (nonlazybind                 . nonlazybind)
     (nonnull                     . nonnull)
     (noredzone                   . noredzone)
     (noreturn                    . noreturn)
     (norecurse                   . norecurse)
     (nounwind                    . nounwind)
     (optimizenone                . optnone)
     (optimizeforsize             . optsize)
     (readnone                    . readnone)
     (readonly                    . readonly)
     (writeonly                   . writeonly)
     (returned                    . returned)
     (returnstwice                . returns_twice)
     (sext                        . signext)
     (speculatable                . speculatable)
     (stackprotect                . ssp)
     (stackprotectreq             . sspreq)
     (stackprotectstrong          . sspstrong)
     (safestack                   . safestack)
     (structret                   . sret)
     (sanitizethread              . sanitize_thread)
     (sanitizememory              . sanitize_memory)
     (uwtable                     . uwtable)
     (zext                        . zeroext)
     (cold                        . cold))))
