#lang racket
(require
  "define.rkt"
  "ctypes.rkt")

(require ffi/unsafe)

(provide (all-defined-out))
; Instruction builders ;
; An instruction builder represents a point within a basic block, and is the
; exclusive means of building instructions using the C interface.

(define-llvm LLVMCreateBuilderInContext    (_fun LLVMContextRef                                                                                                                  -> LLVMBuilderRef))
(define-llvm LLVMCreateBuilder             (_fun                                                                                                                                 -> LLVMBuilderRef))
(define-llvm LLVMPositionBuilder           (_fun LLVMBuilderRef LLVMBasicBlockRef LLVMValueRef                                                                                   -> _void))
(define-llvm LLVMPositionBuilderBefore     (_fun LLVMBuilderRef LLVMValueRef                                                                                                     -> _void))
(define-llvm LLVMPositionBuilderAtEnd      (_fun LLVMBuilderRef LLVMBasicBlockRef                                                                                                -> _void))
(define-llvm LLVMGetInsertBlock            (_fun LLVMBuilderRef                                                                                                                  -> LLVMBasicBlockRef))
(define-llvm LLVMClearInsertionPosition    (_fun LLVMBuilderRef                                                                                                                  -> _void))
(define-llvm LLVMInsertIntoBuilder         (_fun LLVMBuilderRef LLVMValueRef                                                                                                     -> _void))
(define-llvm LLVMInsertIntoBuilderWithName (_fun LLVMBuilderRef LLVMValueRef _string                                                                                             -> _void))
(define-llvm LLVMDisposeBuilder            (_fun LLVMBuilderRef                                                                                                                  -> _void))
(define-llvm LLVMSetCurrentDebugLocation   (_fun LLVMBuilderRef LLVMValueRef                                                                                                     -> _void))
(define-llvm LLVMGetCurrentDebugLocation   (_fun LLVMBuilderRef                                                                                                                  -> LLVMValueRef))
(define-llvm LLVMSetInstDebugLocation      (_fun LLVMBuilderRef LLVMValueRef                                                                                                     -> _void))
(define-llvm LLVMBuildRetVoid              (_fun LLVMBuilderRef                                                                                                                  -> LLVMValueRef))
(define-llvm LLVMBuildRet                  (_fun LLVMBuilderRef LLVMValueRef                                                                                                     -> LLVMValueRef))
(define-llvm LLVMBuildAggregateRet         (_fun LLVMBuilderRef [retvals : (_list i LLVMValueRef)] [_uint = (length retvals)]                                                    -> LLVMValueRef))
(define-llvm LLVMBuildBr                   (_fun LLVMBuilderRef LLVMBasicBlockRef                                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildCondBr               (_fun LLVMBuilderRef LLVMValueRef LLVMBasicBlockRef LLVMBasicBlockRef                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildSwitch               (_fun LLVMBuilderRef LLVMValueRef LLVMBasicBlockRef _uint                                                                             -> LLVMValueRef))
(define-llvm LLVMBuildIndirectBr           (_fun LLVMBuilderRef LLVMValueRef _uint                                                                                               -> LLVMValueRef))
(define-llvm LLVMBuildInvoke               (_fun LLVMBuilderRef LLVMValueRef [args : (_list i LLVMValueRef)] [_uint = (length args)] LLVMBasicBlockRef LLVMBasicBlockRef _string -> LLVMValueRef))
(define-llvm LLVMBuildLandingPad           (_fun LLVMBuilderRef LLVMTypeRef LLVMValueRef _uint _string                                                                           -> LLVMValueRef))
(define-llvm LLVMBuildResume               (_fun LLVMBuilderRef LLVMValueRef                                                                                                     -> LLVMValueRef))
(define-llvm LLVMBuildUnreachable          (_fun LLVMBuilderRef                                                                                                                  -> LLVMValueRef))
(define-llvm LLVMAddCase                   (_fun LLVMValueRef LLVMValueRef LLVMBasicBlockRef                                                                                     -> _void))
(define-llvm LLVMAddDestination            (_fun LLVMValueRef LLVMBasicBlockRef                                                                                                  -> _void))
(define-llvm LLVMAddClause                 (_fun LLVMValueRef LLVMValueRef                                                                                                       -> _void))
(define-llvm LLVMSetCleanup                (_fun LLVMValueRef LLVMBool                                                                                                           -> _void))
(define-llvm LLVMBuildAdd                  (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildNSWAdd               (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildNUWAdd               (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildFAdd                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildSub                  (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildNSWSub               (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildNUWSub               (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildFSub                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildMul                  (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildNSWMul               (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildNUWMul               (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildFMul                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildUDiv                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildSDiv                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildExactSDiv            (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildFDiv                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildURem                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildSRem                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildFRem                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildShl                  (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildLShr                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildAShr                 (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildAnd                  (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildOr                   (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildXor                  (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildBinOp                (_fun LLVMBuilderRef LLVMOpcode LLVMValueRef LLVMValueRef _string                                                                     -> LLVMValueRef))
(define-llvm LLVMBuildNeg                  (_fun LLVMBuilderRef LLVMValueRef _string                                                                                             -> LLVMValueRef))
(define-llvm LLVMBuildNSWNeg               (_fun LLVMBuilderRef LLVMValueRef _string                                                                                             -> LLVMValueRef))
(define-llvm LLVMBuildNUWNeg               (_fun LLVMBuilderRef LLVMValueRef _string                                                                                             -> LLVMValueRef))
(define-llvm LLVMBuildFNeg                 (_fun LLVMBuilderRef LLVMValueRef _string                                                                                             -> LLVMValueRef))
(define-llvm LLVMBuildNot                  (_fun LLVMBuilderRef LLVMValueRef _string                                                                                             -> LLVMValueRef))
(define-llvm LLVMBuildMalloc               (_fun LLVMBuilderRef LLVMTypeRef _string                                                                                              -> LLVMValueRef))
(define-llvm LLVMBuildArrayMalloc          (_fun LLVMBuilderRef LLVMTypeRef LLVMValueRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildAlloca               (_fun LLVMBuilderRef LLVMTypeRef _string                                                                                              -> LLVMValueRef))
(define-llvm LLVMBuildArrayAlloca          (_fun LLVMBuilderRef LLVMTypeRef LLVMValueRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildFree                 (_fun LLVMBuilderRef LLVMValueRef                                                                                                     -> LLVMValueRef))
(define-llvm LLVMBuildLoad                 (_fun LLVMBuilderRef LLVMValueRef _string                                                                                             -> LLVMValueRef))
(define-llvm LLVMBuildStore                (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef                                                                                        -> LLVMValueRef))
(define-llvm LLVMBuildGEP                  (_fun LLVMBuilderRef LLVMValueRef (indices : (_list i LLVMValueRef)) (len : _uint = (length indices)) _string                         -> LLVMValueRef))
(define-llvm LLVMBuildInBoundsGEP          (_fun LLVMBuilderRef LLVMValueRef (indices : (_list i LLVMValueRef)) (len : _uint = (length indices)) _string                         -> LLVMValueRef))
(define-llvm LLVMBuildStructGEP            (_fun LLVMBuilderRef LLVMValueRef _uint _string                                                                                       -> LLVMValueRef))
(define-llvm LLVMBuildGlobalString         (_fun LLVMBuilderRef _string _string                                                                                                  -> LLVMValueRef))
(define-llvm LLVMBuildGlobalStringPtr      (_fun LLVMBuilderRef _string _string                                                                                                  -> LLVMValueRef))
(define-llvm LLVMGetVolatile               (_fun LLVMValueRef                                                                                                                    -> LLVMBool))
(define-llvm LLVMSetVolatile               (_fun LLVMValueRef LLVMBool                                                                                                           -> _void))
(define-llvm LLVMGetOrdering               (_fun LLVMValueRef                                                                                                                    -> LLVMAtomicOrdering))
(define-llvm LLVMSetOrdering               (_fun LLVMValueRef LLVMAtomicOrdering                                                                                                 -> _void))
(define-llvm LLVMBuildTrunc                (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildZExt                 (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildSExt                 (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildFPToUI               (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildFPToSI               (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildUIToFP               (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildSIToFP               (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildFPTrunc              (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildFPExt                (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildPtrToInt             (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildIntToPtr             (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildBitCast              (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildAddrSpaceCast        (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildZExtOrBitCast        (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildSExtOrBitCast        (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildTruncOrBitCast       (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildCast                 (_fun LLVMBuilderRef LLVMOpcode LLVMValueRef LLVMTypeRef _string                                                                      -> LLVMValueRef))
(define-llvm LLVMBuildPointerCast          (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildIntCast              (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildFPCast               (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildICmp                 (_fun LLVMBuilderRef LLVMIntPredicate LLVMValueRef LLVMValueRef _string                                                               -> LLVMValueRef))
(define-llvm LLVMBuildFCmp                 (_fun LLVMBuilderRef LLVMRealPredicate LLVMValueRef LLVMValueRef _string                                                              -> LLVMValueRef))
(define-llvm LLVMBuildPhi                  (_fun LLVMBuilderRef LLVMTypeRef _string                                                                                              -> LLVMValueRef))
(define-llvm LLVMBuildCall                 (_fun LLVMBuilderRef LLVMValueRef [args : (_list i LLVMValueRef)] [_uint = (length args)] _string                                     -> LLVMValueRef))
(define-llvm LLVMBuildSelect               (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef LLVMValueRef _string                                                                   -> LLVMValueRef))
(define-llvm LLVMBuildVAArg                (_fun LLVMBuilderRef LLVMValueRef LLVMTypeRef _string                                                                                 -> LLVMValueRef))
(define-llvm LLVMBuildExtractElement       (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildInsertElement        (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef LLVMValueRef _string                                                                   -> LLVMValueRef))
(define-llvm LLVMBuildShuffleVector        (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef LLVMValueRef _string                                                                   -> LLVMValueRef))
(define-llvm LLVMBuildExtractValue         (_fun LLVMBuilderRef LLVMValueRef _uint _string                                                                                       -> LLVMValueRef))
(define-llvm LLVMBuildInsertValue          (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _uint _string                                                                          -> LLVMValueRef))
(define-llvm LLVMBuildIsNull               (_fun LLVMBuilderRef LLVMValueRef _string                                                                                             -> LLVMValueRef))
(define-llvm LLVMBuildIsNotNull            (_fun LLVMBuilderRef LLVMValueRef _string                                                                                             -> LLVMValueRef))
(define-llvm LLVMBuildPtrDiff              (_fun LLVMBuilderRef LLVMValueRef LLVMValueRef _string                                                                                -> LLVMValueRef))
(define-llvm LLVMBuildFence                (_fun LLVMBuilderRef LLVMAtomicOrdering LLVMBool _string                                                                              -> LLVMValueRef))
(define-llvm LLVMBuildAtomicRMW            (_fun LLVMBuilderRef LLVMAtomicRMWBinOp LLVMValueRef LLVMValueRef LLVMAtomicOrdering LLVMBool                                         -> LLVMValueRef))
